config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/marketplace:
      branch: master
      repo: https://github.com/cyfronet-fid/marketplace
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.amaranth_careful_porpoise.sh
        container: qc.acc_mist_sad_chipmunk
  QC.Doc:
    repos:
      github.com/cyfronet-fid/marketplace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flint_stoic_viper.sh
        container: qc.doc_copper_enigmatic_armadillo
      github.com/cyfronet-fid/marketplace git:
        commands:
        - /usr/bin/env sh .sqa/script.mauve_happy_griffin.sh
        container: qc.doc_nutmeg_timid_lynx
      github.com/cyfronet-fid/marketplace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.mint_productive_hamster.sh
        container: qc.doc_ebony_smart_catfish
  QC.Lic:
    repos:
      github.com/cyfronet-fid/marketplace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.kiwi_open_groundhog.sh
        container: qc.lic_olive_spirited_iguana
  QC.Met:
    repos:
      github.com/cyfronet-fid/marketplace cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.magenta_open_antelope.sh
        container: qc.met_fandango_articulate_alpaca
  QC.Sty:
    repos:
      github.com/cyfronet-fid/marketplace hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.polar_reckless_koala.sh
        container: qc.sty_red_reflective_hydra
      github.com/cyfronet-fid/marketplace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cobalt_positive_rabbit.sh
        container: qc.sty_burgundy_shrewd_quoll
      github.com/cyfronet-fid/marketplace rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.cadet_delighted_iguana.sh
        container: qc.sty_cherry_scrappy_gull
  QC.Ver:
    repos:
      github.com/cyfronet-fid/marketplace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.onyx_mysterious_giraffe.sh
        container: qc.ver_mustard_respectful_phoenix
timeout: 5400
